PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT DISTINCT ?class ?property ?range ?className ?propertyName ?rangeName ?minCount ?maxCount {
    ?classShape sh:targetClass ?class .

    ### Generate label
    OPTIONAL {
        ?class rdfs:label ?classNameOntology
        FILTER (lang(?classNameOntology)='en')
    }
    OPTIONAL {
        ?classShape dct:title ?classNameShacl
        FILTER (lang(?classNameShacl)='en')
    }
    BIND(
        COALESCE(str(?classNameShacl),str(?classNameOntology),REPLACE(STR(
                                                                          ?class), "^.*?([_\\p{L}][-_\\p{L}\\p{N}]*)$", "$1"))
        AS ?className
    )

    OPTIONAL {
        ?classShape sh:property ?propertyShape .
        ?propertyShape a sh:PropertyShape ;
            sh:path ?property ;

        ### Generate label
        OPTIONAL {
            # bug in ELM model - multiple en props, e.g. for mailbox
            SELECT ?property (sample(?propertyNameXX) AS ?propertyNameOntology) {
                ?property rdfs:label ?propertyNameXX
                FILTER (lang(?propertyNameXX)='en')
            }
            GROUP BY ?property
        }
        OPTIONAL {
            ?propertyShape sh:name ?propertyNameShacl
            FILTER (lang(?propertyNameShacl)='en')
        }
        BIND(
            COALESCE(str(?propertyNameShacl), str(?propertyNameOntology),REPLACE(str(
                                                                                     ?property),"^.*?([_\\p{L}][-_\\p{L}\\p{N}]*)$","$1"))
            AS ?propertyName
        )

        OPTIONAL {
            ?propertyShape sh:minCount ?minCountX .
        }
        BIND(COALESCE(?minCountX,0) AS ?minCount)
        OPTIONAL {
            ?propertyShape sh:maxCount ?maxCountX .
        }
        BIND(COALESCE(?maxCountX,"*") AS ?maxCount)
        OPTIONAL {
            ?propertyShape sh:class ?rangeClass .
            OPTIONAL {
                ?rangeClass rdfs:label ?rangeClassNameX
                FILTER (lang(?rangeClassNameX)='en')
            }
            BIND(
                COALESCE(str(?rangeClassNameX),REPLACE(str(?rangeClass),"^.*?([_\\p{L}][-_\\p{L}\\p{N}]*)$","$1"))
                AS ?rangeClassName
            )
        }
        OPTIONAL {
            ?propertyShape sh:datatype ?rangeDatatypeX .
            BIND(REPLACE(str(?rangeDatatypeX),"^.*?([_\\p{L}][-_\\p{L}\\p{N}]*)$","$1") AS ?rangeDatatype)
        }
        BIND(COALESCE(?rangeClassName,?rangeDatatype,"literal") AS ?rangeName)
        BIND(COALESCE(?rangeClass,?rangeDatatypeX) AS ?range)
    }
}
GROUP BY ?class ?property ?range ?className ?propertyName ?rangeName ?minCount ?maxCount ?classDescription
?propertyDescription
ORDER BY ?className DESC(?propertyName) ?minCount ?maxCount ?rangeName
